name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source_repo }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Apply Kubernetes manifests
        run: |
          try {
            kubectl apply -f k8s/namespace.yaml -ErrorAction Stop
          } catch {
            Write-Host "(already exists)"
          }

          kubectl wait --for=condition=Established --timeout=30s ns/deawkoikid
          kubectl apply -f k8s/
          kubectl get pods -n deawkoikid
          Write-Host "Done"
