name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: [self-hosted,linux]
    env:
      KUBECONFIG: /home/title/.kube/config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 5tuay10bath/deawkoikid-fe

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Debug runner info
        run: |
          echo "Runner OS: $(uname -a)"
          echo "Shell: $SHELL"
      - name: Apply Kubernetes manifests
        shell: bash
        run: |
          kubectl apply -f k8s/namespace.yaml || echo "already exists"
          kubectl wait --for=condition=Established --timeout=90s ns/deawkoikid
          kubectl apply -f k8s/
          kubectl get pods -n deawkoikid
          echo "✅ Done

